import { useEffect, useRef, useState } from 'react'
import { Archive, ArchiveRestore, RotateCcw, Trash2, X } from 'lucide-react'

const K={classes:'ot-classes',groups:'ot-groups',schedule:'ot-schedule',documents:'ot-documents',records:'ot-student-records'}
const read=k=>{try{const v=JSON.parse(localStorage.getItem(K[k]||k)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
const write=(k,v)=>localStorage.setItem(K[k]||k,JSON.stringify(v))
const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`
const snap=()=>({classes:read('classes'),groups:read('groups'),schedule:read('schedule'),documents:read('documents'),records:read('records')})
const name=x=>x.type==='class'?`Sınıf · ${x.data.name}`:x.type==='student'?`Öğrenci · ${x.data.firstName} ${x.data.lastName||''}`:x.type==='group'?`Grup · ${x.data.name}`:x.type==='lesson'?`Ders · ${x.data.lesson||''}`:`Belge · ${x.data.name||''}`

export default function LifecycleOverlay(){
 const [open,setOpen]=useState(null),[trash,setTrash]=useState(()=>read('ot-trash')),prev=useRef(snap()),busy=useRef(false)
 useEffect(()=>write('ot-trash',trash),[trash])
 useEffect(()=>{const tick=()=>{if(busy.current)return;const n=snap(),p=prev.current,t=read('ot-trash'),seen=new Set(t.map(x=>`${x.type}:${x.data?.id}`)),add=[]
  const put=(type,data,extra={})=>{if(!data?.id||seen.has(`${type}:${data.id}`))return;seen.add(`${type}:${data.id}`);add.push({id:id(),type,data,...extra,deletedAt:new Date().toISOString()})}
  const nc=new Set(n.classes.map(x=>x.id));for(const c of p.classes)if(!nc.has(c.id))put('class',c,{groups:p.groups.filter(g=>(g.classIds||[]).includes(c.id)),schedule:p.schedule.filter(s=>s.classId===c.id),documents:p.documents.filter(d=>(d.targetType==='class'&&d.targetId===c.id)||(d.targetType==='student'&&(c.students||[]).some(s=>s.id===d.targetId))),records:p.records.filter(r=>(c.students||[]).some(s=>s.id===r.studentId))})
  const ns=new Set(n.classes.flatMap(c=>(c.students||[]).map(s=>`${c.id}:${s.id}`)));for(const c of p.classes)for(const s of c.students||[])if(!ns.has(`${c.id}:${s.id}`)&&nc.has(c.id))put('student',s,{classId:c.id,documents:p.documents.filter(d=>d.targetType==='student'&&d.targetId===s.id),records:p.records.filter(r=>r.studentId===s.id)})
  const cmp=(type,a,b)=>{const ids=new Set(b.map(x=>x.id));for(const x of a)if(!ids.has(x.id))put(type,x)};cmp('group',p.groups,n.groups);cmp('lesson',p.schedule,n.schedule);cmp('document',p.documents,n.documents)
  if(add.length)setTrash(v=>[...v,...add]);prev.current=n};const timer=setInterval(tick,700);return()=>clearInterval(timer)},[])
 const archive=id=>{write('classes',read('classes').map(c=>c.id===id?{...c,archivedAt:new Date().toISOString(),academicYear:c.academicYear||`${new Date().getFullYear()}-${new Date().getFullYear()+1}`}:c));location.reload()}
 const unarchive=id=>{write('classes',read('classes').map(c=>{if(c.id!==id)return c;const x={...c};delete x.archivedAt;return x}));location.reload()}
 const restore=x=>{busy.current=true;try{if(x.type==='class'){if(!read('classes').some(c=>c.id===x.data.id))write('classes',[...read('classes'),x.data]);for(const k of ['groups','schedule','documents','records'])if(Array.isArray(x[k])){const a=read(k),ids=new Set(a.map(v=>v.id));write(k,[...a,...x[k].filter(v=>!ids.has(v.id))])}}else if(x.type==='student'){write('classes',read('classes').map(c=>c.id===x.classId&&!(c.students||[]).some(s=>s.id===x.data.id)?{...c,students:[...(c.students||[]),x.data]}:c));for(const k of ['documents','records'])if(Array.isArray(x[k])){const a=read(k),ids=new Set(a.map(v=>v.id));write(k,[...a,...x[k].filter(v=>!ids.has(v.id))])}}else{const k=x.type==='group'?'groups':x.type==='lesson'?'schedule':'documents';const a=read(k);if(!a.some(v=>v.id===x.data.id))write(k,[...a,x.data])}setTrash(v=>v.filter(v=>v.id!==x.id));location.reload()}finally{busy.current=false}}
 const active=read('classes').filter(c=>!c.archivedAt),archived=read('classes').filter(c=>c.archivedAt)
 return <><div style={s.launch}><button className="secondary" onClick={()=>setOpen(open==='a'?null:'a')}><Archive size={15}/> Arşiv</button><button className="secondary" onClick={()=>setOpen(open==='t'?null:'t')}><Trash2 size={15}/> Çöp Kutusu{trash.length?` (${trash.length})`:''}</button></div>{open&&<div style={s.back} onMouseDown={()=>setOpen(null)}><section style={s.panel} onMouseDown={e=>e.stopPropagation()}><header style={s.head}><div><b>{open==='a'?'Arşiv':'Çöp Kutusu'}</b><small>{open==='a'?'Arşivlenen sınıflar':'Silinen kayıtlar'}</small></div><button className="icon-btn" onClick={()=>setOpen(null)}><X size={17}/></button></header>{open==='a'?<div style={s.list}>{archived.map(c=><div style={s.row} key={c.id}><span><b>{c.name}</b><small>{c.students?.length||0} öğrenci · {c.academicYear||'Arşiv'}</small></span><button className="secondary" onClick={()=>unarchive(c.id)}><ArchiveRestore size={14}/> Geri Al</button></div>)}{!archived.length&&<div className="empty">Arşiv boş.</div>}<b style={s.sub}>Aktif sınıflar</b>{active.map(c=><div style={s.row} key={c.id}><span><b>{c.name}</b><small>{c.students?.length||0} öğrenci</small></span><button className="secondary" onClick={()=>archive(c.id)}><Archive size={14}/> Arşivle</button></div>)}</div>:<div style={s.list}>{trash.slice().reverse().map(x=><div style={s.row} key={x.id}><span><b>{name(x)}</b><small>{new Date(x.deletedAt).toLocaleString('tr-TR')}</small></span><div style={{display:'flex',gap:6}}><button className="secondary" onClick={()=>restore(x)}><RotateCcw size={14}/> Geri Yükle</button><button className="icon-btn danger" onClick={()=>setTrash(v=>v.filter(y=>y.id!==x.id))}><Trash2 size={14}/></button></div></div>)}{!trash.length&&<div className="empty">Çöp kutusu boş.</div>}{trash.length>0&&<button className="danger-outline" onClick={()=>setTrash([])}>Çöp Kutusunu Boşalt</button>}</div>}</section></div>}</>}
const s={launch:{position:'fixed',left:14,bottom:14,zIndex:45,display:'flex',gap:7},back:{position:'fixed',inset:0,zIndex:90,background:'rgba(12,20,34,.38)',display:'grid',placeItems:'center',padding:16},panel:{width:'min(760px,100%)',maxHeight:'calc(100vh - 32px)',overflow:'auto',background:'#fff',borderRadius:18,padding:18,boxShadow:'0 24px 80px rgba(10,20,40,.24)'},head:{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14},list:{display:'grid',gap:7},row:{border:'1px solid #e7ebf0',borderRadius:11,padding:11,display:'flex',alignItems:'center',justifyContent:'space-between',gap:10},sub:{display:'block',fontSize:11,color:'#7a8497',margin:'14px 0 5px'}}
