import { useMemo, useState } from 'react'
import { Bell, CalendarDays, ChevronLeft, ChevronRight, FileText, Home as HomeIcon, LayoutGrid, Megaphone, MoreHorizontal, Plus, Search, Star, UserRound, UsersRound, Zap } from 'lucide-react'
import './referenceDashboard.css'

const trDate = (d) => d.toLocaleDateString('tr-TR', { weekday:'long', day:'numeric', month:'long' })
const trMonth = (d) => d.toLocaleDateString('tr-TR', { month:'long', year:'numeric' })

export default function ReferenceDashboard({ classes=[], schedule=[], documents=[], search='', setSearch=()=>{}, onClass=()=>{}, onClasses=()=>{}, onSchedule=()=>{}, onAddClass=()=>{}, onNewStudent=()=>{}, onDocument=()=>{} }) {
  const now = new Date()
  const [month, setMonth] = useState(new Date(now.getFullYear(), now.getMonth(), 1))
  const lessons = useMemo(() => schedule.filter(x => x.scope !== 'classProgram' && x.day === ((now.getDay()+6)%7)).sort((a,b)=>String(a.start).localeCompare(String(b.start))).slice(0,3), [schedule, now])
  const visible = classes.filter(c => c.name.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))).slice(0,4)
  const first = new Date(month.getFullYear(), month.getMonth(), 1)
  const days = new Date(month.getFullYear(), month.getMonth()+1, 0).getDate()
  const lead = (first.getDay()+6)%7
  const cells = Array.from({length: lead+days}, (_,i) => i<lead ? null : i-lead+1)
  let recentDocs=[]
  try { recentDocs = JSON.parse(localStorage.getItem('ot-documents')||'[]').slice(0,3) } catch {}
  const notes = classes.flatMap(c => (c.students||[]).map(s => ({name:`${s.firstName} ${s.lastName}`.trim(), cls:c.name, text:s.note||s.notes||''}))).filter(x=>x.text).slice(0,3)
  return <main className="reference-dashboard">
    <header className="reference-topbar"><div className="reference-search"><Search size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Sınıf veya öğrenci ara…"/></div><div className="reference-user"><button className="reference-bell"><Bell size={23}/><i/></button><span className="reference-avatar">SB</span><b>Serbay Bağcı</b><ChevronDown size={17}/></div></header>
    <section className="reference-hero"><div><p>İyi bir gün olsun <span>🌿</span></p><h1>{trDate(now)}</h1><small>Bugün de harika işler başaracaksın.</small></div><div className="reference-leaves"><i/><i/><i/><i/><i/></div></section>
    <div className="reference-grid"><div className="reference-main">
      <div className="reference-top-cards"><section className="ref-card lessons"><div className="ref-head"><h2><CalendarDays size={21}/> Bugünün Dersleri</h2><button onClick={onSchedule}>Tümünü Gör <ChevronRight size={16}/></button></div>{lessons.length?lessons.map((x,i)=><button className="ref-lesson" key={x.id} onClick={()=>onClass(x.classId)}><span className="ref-time"><i/>{x.start} – {x.end}</span><span className="ref-lesson-class"><span className="ref-blue-icon"><UsersRound size={22}/></span><span><b>{classes.find(c=>c.id===x.classId)?.name||'—'}</b><small>{x.lesson}</small></span></span><em>{i===0?'Şimdi':i===1?'Yaklaşıyor':''}</em></button>):<div className="ref-empty">Bugün için ders bulunmuyor.</div>}</section>
      <section className="ref-card quick"><div className="ref-head"><h2><Zap size={21}/> Hızlı İşlemler</h2></div><div className="ref-quick-grid"><button onClick={onNewStudent}><UserRound/><span>Yeni Öğrenci</span></button><button onClick={onAddClass}><UsersRound/><span>Sınıf Ekle</span></button><button onClick={onDocument}><FileText/><span>Belge Ekle</span></button><button onClick={onSchedule}><CalendarDays/><span>Ders Programı</span></button></div></section></div>
      <section className="ref-card ref-classes"><div className="ref-head"><h2><UsersRound size={21}/> Sınıflarım</h2><div><button onClick={onClasses}>Tümünü Gör <ChevronRight size={16}/></button><button className="ref-plus" onClick={onAddClass}><Plus size={21}/></button></div></div><div className="ref-class-grid">{visible.map((c,i)=><button key={c.id} className={`ref-class c${i}`} onClick={()=>onClass(c.id)}><span><UsersRound size={22}/></span><b>{c.name}<small>{c.students.length} öğrenci</small></b></button>)}{!visible.length&&<div className="ref-empty">Henüz sınıf oluşturulmadı.</div>}</div></section>
      <div className="ref-bottom"><section className="ref-card"><div className="ref-head"><h2><FileText size={21}/> Son Eklenen Belgeler</h2><button onClick={onDocument}>Tümünü Gör <ChevronRight size={16}/></button></div>{recentDocs.length?recentDocs.map((d,i)=><div className="ref-doc" key={d.id}><span className={`ref-file f${i}`}>{String(d.type||'').includes('pdf')?'PDF':String(d.name||'').split('.').pop()?.toUpperCase()||'DOC'}</span><span><b>{d.name}</b><small>{d.targetType==='group'?'Genel':d.targetType==='student'?'Öğrenci':'4-D'} · {d.createdAt?new Date(d.createdAt).toLocaleDateString('tr-TR',{day:'numeric',month:'short'}):'Bugün'} · {d.size?((d.size/1024/1024).toFixed(1)+' MB'):''}</small></span><MoreHorizontal size={18}/></div>):<div className="ref-empty">Henüz belge yüklenmedi.</div>}</section><section className="ref-card"><div className="ref-head"><h2><Megaphone size={21}/> Duyurular</h2><button>Tümünü Gör <ChevronRight size={16}/></button></div><div className="ref-ann"><i/><div><b>Resim Sergisi</b><small>12 Eylül 2025</small><p>Öğrencilerimizin yıl boyunca hazırladığı çalışmalar sergilenecektir.</p></div></div><div className="ref-ann"><i/><div><b>Veli Toplantısı</b><small>18 Eylül 2025</small><p>Tüm velilerimiz davetlidir.</p></div></div></section></div>
    </div><aside className="reference-side"><section className="ref-card ref-calendar"><div className="ref-head"><h2><CalendarDays size={21}/> Takvim</h2><button className="ref-today" onClick={()=>setMonth(new Date(now.getFullYear(),now.getMonth(),1))}>Bugün</button><button className="ref-arrow" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={17}/></button><button className="ref-arrow" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={17}/></button></div><h3>{trMonth(month)}</h3><div className="ref-week">{['Pzt','Sal','Çar','Per','Cum','Cts','Paz'].map(x=><span key={x}>{x}</span>)}</div><div className="ref-days">{cells.map((d,i)=><span key={i} className={d===now.getDate()&&month.getMonth()===now.getMonth()&&month.getFullYear()===now.getFullYear()?'selected':''}>{d||''}</span>)}</div></section><section className="ref-card ref-notes"><div className="ref-head"><h2><FileText size={21}/> Son Notlar</h2><button>Tümünü Gör <ChevronRight size={16}/></button></div>{notes.length?notes.map(n=><div className="ref-note" key={n.name}><span><UserRound size={21}/></span><div><b>{n.name}</b><small>{n.cls} · Bugün</small><p><Star size={13}/>{n.text}</p></div><ChevronRight size={16}/></div>):<div className="ref-empty">Henüz not yok.</div>}</section><section className="ref-quote"><span>“</span><p>Her çocuk özeldir.</p><i/></section></aside></div>
  </main>
}
