import { useEffect, useMemo, useState } from 'react'
import { addStudentRecord, checkStudentRecordIntegrity, deleteStudentRecord } from './studentRecords'

const read=(k,f=[])=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return Array.isArray(v)?v:f}catch{return f}}
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v))
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,9)}`
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const parseDate=v=>{const s=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);return m?`${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`:''}
const labelDate=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric'}):'Belirtilmedi'

export default function StudentOverlayFixed(){
 const [student,setStudent]=useState(null),[version,setVersion]=useState(0),[editing,setEditing]=useState(false),[edit,setEdit]=useState({}),[text,setText]=useState(''),[noteDate,setNoteDate]=useState(today()),[starred,setStarred]=useState(false),[error,setError]=useState('')
 useEffect(()=>{const click=e=>{const row=e.target.closest?.('.student-row');if(!row||e.target.closest('button,a,input,select,textarea'))return;const raw=row.querySelector('b')?.textContent?.trim()||'';const parts=raw.split('·');const number=parts.length>1?parts[0].trim():'';const name=(parts.length>1?parts.slice(1).join('·'):raw).trim();const cls=row.closest('.content')?.querySelector('.detail-head h1')?.textContent?.trim();const all=read('ot-classes');let found=null;for(const c of all){if(cls&&c.name!==cls)continue;found=(c.students||[]).find(s=>(number&&String(s.studentNumber||'')===number)||`${s.firstName} ${s.lastName}`.trim()===name);if(found){found={...found,className:c.name};break}}if(found){setStudent(found);setEdit({...found,birthDate:found.birthDate||''});setEditing(false);setText('');setNoteDate(today());setStarred(false);setError('')}};document.addEventListener('click',click);return()=>document.removeEventListener('click',click)},[])
 useEffect(()=>{if(!student)return;const sync=()=>{const c=read('ot-classes'),r=read('ot-student-records'),x=checkStudentRecordIntegrity(c,r);if(!x.ok)write('ot-student-records',x.records);if(!c.some(a=>(a.students||[]).some(s=>s.id===student.id)))setStudent(null);setVersion(v=>v+1)};sync();const t=setInterval(sync,1000);return()=>clearInterval(t)},[student])
 const records=useMemo(()=>read('ot-student-records').filter(x=>x.studentId===student?.id).sort((a,b)=>`${b.date}${b.updatedAt||b.createdAt}`.localeCompare(`${a.date}${a.updatedAt||a.createdAt}`)),[student,version])
 const docs=useMemo(()=>read('ot-documents').filter(x=>x.targetType==='student'&&x.targetId===student?.id),[student,version])
 if(!student)return null
 const saveEdit=()=>{if(!edit.firstName?.trim()){setError('Öğrenci adı boş bırakılamaz.');return}const birth=parseDate(edit.birthDate);if(edit.birthDate&&!birth){setError('Doğum tarihini GG.AA.YYYY şeklinde girin.');return}const {className,...studentData}=edit;write('ot-classes',read('ot-classes').map(c=>({...c,students:(c.students||[]).map(s=>s.id===student.id?{...s,...studentData,firstName:studentData.firstName.trim(),lastName:(studentData.lastName||'').trim(),studentNumber:String(studentData.studentNumber||'').trim(),birthDate:birth}:s)})));location.reload()}
 const addNote=()=>{try{if(!text.trim()){setError('Not boş bırakılamaz.');return}const now=new Date().toISOString();write('ot-student-records',addStudentRecord(read('ot-student-records'),{studentId:student.id,type:'note',text:text.trim(),starred,date:parseDate(noteDate)||today(),createdAt:now,updatedAt:now},uid()));setText('');setStarred(false);setError('');setVersion(v=>v+1)}catch(e){setError(e.message)}}
 const removeNote=id=>{if(!confirm('Bu kaydı silmek istediğinizden emin misiniz?'))return;write('ot-student-records',deleteStudentRecord(read('ot-student-records'),id));setVersion(v=>v+1)}
 return <div style={s.backdrop} onMouseDown={()=>setStudent(null)}><div style={s.panel} onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true">
  <div style={s.head}><div style={s.identity}><span style={s.avatar}>{student.firstName?.[0]}{student.lastName?.[0]||''}</span><div><small style={s.eyebrow}>ÖĞRENCİ · {student.className}</small><div style={s.titleLine}><h2 style={s.title}>{student.firstName} {student.lastName}</h2></div></div></div><button className="icon-btn" onClick={()=>setStudent(null)}>×</button></div>
  {error&&<div className="auth-error">{error}</div>}
  <section className="card"><div className="section-head"><div className="section-title">Öğrenci Bilgileri</div><button className="secondary small" onClick={()=>{setEditing(!editing);setEdit({...student,birthDate:student.birthDate||''})}}>{editing?'Vazgeç':'Düzenle'}</button></div>
   {editing?<div className="form-grid" style={{marginTop:12}}><label className="field"><span>Öğrenci numarası</span><input value={edit.studentNumber||''} onChange={e=>setEdit({...edit,studentNumber:e.target.value})}/></label><label className="field"><span>Ad</span><input value={edit.firstName||''} onChange={e=>setEdit({...edit,firstName:e.target.value})}/></label><label className="field"><span>Soyad</span><input value={edit.lastName||''} onChange={e=>setEdit({...edit,lastName:e.target.value})}/></label><label className="field"><span>Doğum tarihi</span><input type="text" inputMode="numeric" placeholder="GG.AA.YYYY" value={edit.birthDate||''} onChange={e=>setEdit({...edit,birthDate:e.target.value})}/></label><label className="field"><span>Anne adı soyadı</span><input value={edit.parentName||''} onChange={e=>setEdit({...edit,parentName:e.target.value})}/></label><label className="field"><span>Anne telefonu</span><input value={edit.parentPhone||''} onChange={e=>setEdit({...edit,parentPhone:e.target.value})}/></label><label className="field"><span>Baba adı soyadı</span><input value={edit.secondParentName||''} onChange={e=>setEdit({...edit,secondParentName:e.target.value})}/></label><label className="field"><span>Baba telefonu</span><input value={edit.secondParentPhone||''} onChange={e=>setEdit({...edit,secondParentPhone:e.target.value})}/></label><label className="field" style={{gridColumn:'1/-1'}}><span>Adres</span><textarea value={edit.address||''} onChange={e=>setEdit({...edit,address:e.target.value})}/></label><button className="primary" onClick={saveEdit}>Bilgileri Kaydet</button></div>:<div style={s.infoGrid}>{[['Doğum tarihi',labelDate(student.birthDate)],['Anne adı soyadı',student.parentName],['Anne telefonu',student.parentPhone],['Baba adı soyadı',student.secondParentName],['Baba telefonu',student.secondParentPhone],['Adres',student.address]].map(([k,v])=><div key={k} style={s.infoItem}><small>{k}</small><b>{v||'Belirtilmedi'}</b></div>)}</div>}
  </section>
  <section className="card"><div className="section-head"><div><div className="section-title">Not Ekle</div><p className="muted">Öğrenciyle ilgili önemli bilgileri tarihçeye ekle.</p></div><label className="star-note"><input type="checkbox" checked={starred} onChange={e=>setStarred(e.target.checked)}/> ★ Yıldızlı not</label></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Öğrenci hakkında not…" style={s.textarea}/><div className="modal-actions"><label className="field"><span>Tarih</span><input type="text" inputMode="numeric" placeholder="GG.AA.YYYY" value={noteDate} onChange={e=>setNoteDate(e.target.value)}/></label><button className="primary" onClick={addNote}>Notu Kaydet</button></div></section>
  <section className="card"><div className="section-head"><div><div className="section-title">Öğrenci Geçmişi</div><p className="muted">Notlar, olaylar ve yoklama kayıtları</p></div><span className="hint">{records.length} kayıt</span></div><div style={s.history}>{records.map(r=><div key={r.id} style={s.record}><div style={s.recordTop}><b>{r.starred?'★ ':''}Not</b><small>{labelDate(r.date)}</small></div><div style={s.recordBody}>{r.text||r.status||'—'}</div><button className="icon-btn danger" onClick={()=>removeNote(r.id)}>×</button></div>)}{!records.length&&<div className="empty">Bu öğrenci için henüz kayıt yok.</div>}</div></section>
  {docs.length>0&&<section className="card"><div className="section-title">Öğrenci Belgeleri</div><div style={s.docs}>{docs.map(d=><a key={d.id} href={d.downloadUrl||d.data} target="_blank" rel="noreferrer" style={s.doc}>{d.name}<span>{d.type||'Belge'}</span></a>)}</div></section>}
 </div></div>
}
const s={backdrop:{position:'fixed',inset:0,zIndex:100,background:'rgba(12,20,34,.46)',display:'grid',placeItems:'center',padding:16},panel:{width:'min(900px,100%)',maxHeight:'calc(100vh - 32px)',overflow:'auto',background:'#f5f7fb',borderRadius:20,padding:18,boxShadow:'0 24px 80px rgba(10,20,40,.28)'},head:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,marginBottom:14},identity:{display:'flex',alignItems:'center',gap:11},avatar:{width:48,height:48,borderRadius:'50%',background:'#e7ebf1',display:'grid',placeItems:'center',fontWeight:800,color:'#536076'},eyebrow:{display:'block',color:'#7a8497',fontSize:10,fontWeight:800,letterSpacing:'.08em',marginBottom:3},titleLine:{display:'flex',alignItems:'baseline',gap:10,flexWrap:'wrap'},title:{margin:0,fontSize:24,color:'#172033'},infoGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:12},infoItem:{border:'1px solid #edf0f4',borderRadius:10,padding:'10px 12px',background:'#fafbfc',display:'grid',gap:4},textarea:{width:'100%',minHeight:84,resize:'vertical',border:'1px solid #dfe4eb',borderRadius:9,padding:10,font:'inherit'},history:{display:'grid',gap:7},record:{position:'relative',border:'1px solid #edf0f4',borderRadius:11,padding:11,paddingRight:48,background:'#fafbfc'},recordTop:{display:'flex',gap:10,alignItems:'center'},recordBody:{marginTop:5,color:'#4f5b6e',fontSize:12,whiteSpace:'pre-wrap'},docs:{display:'grid',gap:7,marginTop:12},doc:{display:'flex',justifyContent:'space-between',gap:10,border:'1px solid #edf0f4',borderRadius:10,padding:10,color:'#415a7a',textDecoration:'none',fontSize:12}}
