import { useEffect } from 'react'
import * as XLSX from 'xlsx'

const clean=v=>String(v??'').replace(/\uFEFF/g,'').replace(/\s+/g,' ').trim()
const key=(a,b)=>`${clean(a)} ${clean(b)}`.toLocaleLowerCase('tr-TR').replace(/\s+/g,' ').trim()
const iso=v=>{const s=clean(v);if(!s)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;let m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);if(m)return `${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`;m=s.match(/^(\d{4})[./-](\d{1,2})[./-](\d{1,2})$/);if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;const n=Number(s);if(Number.isFinite(n)&&n>20000&&n<60000){const d=XLSX.SSF.parse_date_code(n);if(d)return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`};return ''}
const birthMap=raw=>{const h=(raw[0]||[]).map(clean).map(x=>x.toLocaleLowerCase('tr-TR'));const find=(names,f)=>names.map(x=>h.indexOf(x)).find(i=>i>=0)??f;const ni=find(['öğrenci no','ogrenci no','öğrenci numarası','ogrenci numarasi','student number','studentnumber'],1),fi=find(['ad','adı','isim','first name','firstname'],2),li=find(['soyad','soyadı','last name','lastname'],3),bi=find(['doğum tarihi','dogum tarihi','birth date','birthdate'],5);const m={n:{},s:{},count:0};raw.slice(1).forEach(r=>{const b=iso(r?.[bi]),n=clean(r?.[ni]),f=clean(r?.[fi]),l=clean(r?.[li]);if(!b)return;if(n)m.n[n]=b;if(f||l)m.s[key(f,l)]=b;m.count++});return m}
const apply=(m)=>{try{const cs=JSON.parse(localStorage.getItem('ot-classes')||'[]');if(!Array.isArray(cs))return 0;let changed=0;const next=cs.map(c=>({...c,students:(c.students||[]).map(s=>{const b=m.n[clean(s.studentNumber)]||m.s[key(s.firstName,s.lastName)];if(b&&s.birthDate!==b){changed++;return {...s,birthDate:b}}return s})}));if(changed)localStorage.setItem('ot-classes',JSON.stringify(next));return changed}catch{return 0}}
export default function UXFixes(){useEffect(()=>{const inputFix=()=>document.querySelectorAll('.field').forEach(f=>{const label=clean(f.querySelector('span')?.textContent),i=f.querySelector('input[type="date"],input[placeholder="GG.AA.YYYY"]');if(label==='Doğum tarihi'&&i){i.type='text';i.inputMode='numeric';i.placeholder='GG.AA.YYYY'}});inputFix();const obs=new MutationObserver(inputFix);obs.observe(document.body,{childList:true,subtree:true});const onBlur=e=>{const i=e.target;if(i instanceof HTMLInputElement&&i.placeholder==='GG.AA.YYYY'){const b=iso(i.value);if(b){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;setter?.call(i,b);i.dispatchEvent(new Event('input',{bubbles:true}))}}};const onFile=async e=>{const i=e.target;if(!(i instanceof HTMLInputElement)||i.type!=='file'||!i.files?.[0])return;try{const wb=XLSX.read(await i.files[0].arrayBuffer(),{type:'array',raw:false}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});window.__otImportBirthDates=birthMap(raw);window.__otBirthAttempts=0}catch{window.__otImportBirthDates=null}};document.addEventListener('blur',onBlur,true);document.addEventListener('change',onFile,true);const timer=setInterval(()=>{const m=window.__otImportBirthDates;if(!m?.count)return;window.__otBirthAttempts=(window.__otBirthAttempts||0)+1;const changed=apply(m);if(changed||window.__otBirthAttempts>60){delete window.__otImportBirthDates;delete window.__otBirthAttempts}},250);return()=>{obs.disconnect();document.removeEventListener('blur',onBlur,true);document.removeEventListener('change',onFile,true);clearInterval(timer)}},[]);return null}
